import mediaDevices from 'react-native-webrtc/lib/typescript/MediaDevices';
import MediaStream from 'react-native-webrtc/lib/typescript/MediaStream';
import MediaStreamTrack from 'react-native-webrtc/lib/typescript/MediaStreamTrack';
import permissions from 'react-native-webrtc/lib/typescript/Permissions';
import RTCErrorEvent from 'react-native-webrtc/lib/typescript/RTCErrorEvent';
import RTCIceCandidate from 'react-native-webrtc/lib/typescript/RTCIceCandidate';
import RTCPeerConnection from 'react-native-webrtc/lib/typescript/RTCPeerConnection';
import RTCRtpReceiver from 'react-native-webrtc/lib/typescript/RTCRtpReceiver';
import RTCRtpSender from 'react-native-webrtc/lib/typescript/RTCRtpSender';
import RTCRtpTransceiver from 'react-native-webrtc/lib/typescript/RTCRtpTransceiver';
import RTCSessionDescription from 'react-native-webrtc/lib/typescript/RTCSessionDescription';
import RTCView from 'react-native-webrtc/lib/typescript/RTCView';
import ScreenCapturePickerView from 'react-native-webrtc/lib/typescript/ScreenCapturePickerView';
export { RTCIceCandidate, RTCPeerConnection, RTCSessionDescription, RTCView, ScreenCapturePickerView, RTCRtpTransceiver, RTCRtpReceiver, RTCRtpSender, RTCErrorEvent, MediaStream, MediaStreamTrack, mediaDevices, permissions, registerGlobals };
declare function registerGlobals(): void;
